export const IPC_CHANNELS = {
  SERVERS_LIST: 'servers:list',
  SERVERS_CREATE: 'servers:create',
  SERVERS_UPDATE: 'servers:update',
  SERVERS_DELETE: 'servers:delete',
  SERVERS_TOGGLE_FAVORITE: 'servers:toggleFavorite',
  SSH_CONNECT: 'ssh:connect',
  SSH_DISCONNECT: 'ssh:disconnect',
  SSH_TEST: 'ssh:test',
  SSH_GET_STATUS: 'ssh:getStatus',
  SSH_GET_METRICS: 'ssh:getMetrics',
  SFTP_LIST: 'sftp:list',
  SFTP_READ_FILE: 'sftp:readFile',
  SFTP_WRITE_FILE: 'sftp:writeFile',
  FS_GET_PATHS: 'fs:getPaths',
  FS_LIST: 'fs:list',
  FS_READ_FILE: 'fs:readFile',
  FS_WRITE_FILE: 'fs:writeFile',
} as const
